server:
  port: 80



spring:
  application:
    name: order-feign

ribbon:
  ReadTimeout:  5000 #建立连接所需最长时间
  ConnectTimeout: 5000 #建立连接之后最长响应时间
#开启feign客户端请求打印日志
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka   #单机配置
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  #集群配置
  instance:
    instance-id: order-80  #这个是修改Eureka界面的Status名称
    prefer-ip-address: true    #这个是设置鼠标放在status上的时候，出现的提示，设置ip地址显示


logging:
  level:
    com.cloud.order.service.PaymentFeignService: debug

