server:
  port: 80


eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka   #单机配置
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  #集群配置
  instance:
    instance-id: order-80  #这个是修改Eureka界面的Status名称
    prefer-ip-address: true    #这个是设置鼠标放在status上的时候，出现的提示，设置ip地址显示
    lease-renewal-interval-in-seconds: 30  #eureka向服务端发送心跳的时间间隔默认为30秒
    lease-expiration-duration-in-seconds: 90   #eureka最后收到心跳之后等待时间默认为90秒
spring:
  application:
    name: order-service
