server:
  port: 80

feign:
  hystrix:
    enabled: true
eureka:
  client:
    register-with-eureka: true    #表识不向注册中心注册自己
    fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: order-hystrix-80  #这个是修改Eureka界面的Status名称
    prefer-ip-address: true    #这个是设置鼠标放在status上的时候，出现的提示，设置ip地址显示
    lease-renewal-interval-in-seconds: 30  #eureka向服务端发送心跳的时间间隔默认为30秒
    lease-expiration-duration-in-seconds: 90   #eureka最后收到心跳之后等待时间默认为90秒
spring:
  application:
    name: order-hystrix